version: '3.2'

services:
  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - "${MYSQL_PORT_LOCAL:-/3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secretpassword
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=shopix
      - MYSQL_ROOT_HOST=%
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: