version: '3.2'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secretpassword
      - MYSQL_USER=TestUser
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=shopix
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

