<?php

namespace ContainerKWx69IP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getManagerRegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.o6sN0hZ.Doctrine\Persistence\ManagerRegistry' shared service.
     *
     * @return \Doctrine\Persistence\ManagerRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.o6sN0hZ": it references interface "Doctrine\\Persistence\\ManagerRegistry" but no such service exists. Did you create a class that implements this interface?');
    }
}
