<?php

declare(strict_types=1);

namespace AppTest\Controller;

use App\Controller\DetailControll;
use App\Controller\HomeControll;
use App\Controller\ListControll;
use PHPUnit\Framework\TestCase;

class ControllerTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->detailController = new DetailControll();
        $this->homeController = new HomeControll();
        $this->listController = new ListControll();
    }

    public function testDetailController(): void
    {
        $itemsForProduct = ['id', 'value'];
        self::assertEquals(['id', 'value'], $itemsForProduct);
    }

    public function testHomeController(): void
    {
        $itemsForParameter = ['id', 'value'];
        self::assertEquals(['id', 'value'], $itemsForParameter);
    }

    public function testListController(): void
    {
        $itemsForCategory = ['id', 'value'];
        self::assertEquals(['id', 'value'], $itemsForCategory);
    }
}