<?php

declare(strict_types=1);

namespace AppTest\Controller;

use App\Controller\DetailControll;

use App\Controller\HomeControll;
use App\Core\View;
use PHPUnit\Framework\TestCase;


class DetailControllerTest extends TestCase
{
    protected function tearDown(): void
    {
        $_GET =[];
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testDisplay(): void
    {
        $_GET['id'] = 10;

        $view = new View($this->createStub(\Smarty::class));

        $detailController = new DetailControll($view, ['categoryId' => '1', 'id' => '1']);
        $detailController->renderView();

        var_dump($view->getParams());
    }
}